name = "JSMDAstroRepresentations"
uuid = "403ab190-7cad-4c95-848f-e576570a949d"
authors = ["Andrea Pasquale"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
